### ISSUE TITLE
windows 10 1903 latest update stucking

### ISSUE THREAD

**Issue by InvisK** [btbd/access#1]
hello, i've loaded driver but after inject dll to CE it's stucking when selecting process, im using windows 10 1903 latest update, can you help to fix it ?

**Comment by btbd** [comment]
Attach a debugger and let me know where it is getting "stuck". I'm not sure why/where it would get stuck instead of throwing an error.

**Comment by InvisK** [comment]
well im tried to debug but it's look like the dll cant communicate with the sys, maybe NtGdiDdDDIGetSharedResourceAdapterLuid now not call to DxgkGetSharedResourceAdapterLuid ?

**Comment by btbd** [comment]
Doubt it. I tested on a 1909 VM and works properly. Open up DbgView to see the debug output of the driver -- is the driver entry succeeding?

**Comment by InvisK** [comment]
sure, it show "[dbg]success", i also add a testing log at begin of function "DxgkGetSharedResourceAdapterLuidHook" but its not output anything, can i ask whats your CE base version?

**Comment by btbd** [comment]
The CE version shouldn't matter as it hooks NTDLL syscall stubs, so it will work for any x64 process. Anyways, I tested it on both 6.8.3 and 7.0.

I'm not sure what else to say with regards to DxgkGetSharedResourceAdapterLuid not being called by the usermode syscall considering you're on 1903. Try putting a breakpoint on dxgkrnl!DxgkGetSharedResourceAdapterLuid and check if it's called from NtGdiDdDDIGetSharedResourceAdapterLuid. On every VM I have from 1803-1909 it is reached.

**Comment by btbd** [comment]
If you can't figure it out, I've put a different communication method on [this branch](https://github.com/btbd/access/tree/noseh). This branch also contains the implementation without SEH so it can be manually mapped. Although if you are not manually mapping the driver, then you can simply change the communication to be an IOCTL rather than this mess.
