### ISSUE TITLE
you project ce debug bypass possible?

### ISSUE THREAD

**Issue by kitty8904** [btbd/access#2]
<img width="1275" alt="1" src="https://user-images.githubusercontent.com/18622105/69559982-4f94b400-0fee-11ea-91d3-a4ef44dfcc86.png">

Default ce windows debug no access crash

1. dbvm nomal debug -> no access read & write breakpoint
2. default windows debug -> no access process select crash

veh or dbvm have a detection vector

Normal windows cannot connect to debug access

Can I connect debug stubs with the kernel to bypass debug detection?

**Comment by btbd** [comment]
This purpose of this project is to bypass handle detection and has nothing to do with bypassing anti-debug techinques. See [TitanHide](https://github.com/mrexodia/TitanHide) or [ScyllaHide](https://github.com/x64dbg/ScyllaHide).
