### ISSUE TITLE
CE Debugger cant Attach to any process

### ISSUE THREAD

**Issue by Flerov** [btbd/access#20]
Using this project everything works like a charm.
But as soon as I try to Attach the CE-Debugger to "check what writes this address" I get a CE-Error that it cannot attach the debugger.
But without the dll injected into CE the same works.
Any ideas...
Do I need to add some apis to make this work or why could this be?

**Comment by ghost** [comment]
This project give only access to kernel memory management, not more. If you need debugger, you can try kernel debugger inside Cheat Engine, but for most games with kernel anticheat it will not work I think.
