### ISSUE TITLE
Failed to hook "NtProtectVirtualMemory"

### ISSUE THREAD

**Issue by Solitrek** [btbd/access#23]
After hours of modifying CE I injected the DLL and it gave me this error, tried searching for it but not much answers
I'm on Windows 11
![Screenshot 2023-08-18 232425](https://github.com/btbd/access/assets/131033196/eedfc9d8-8757-4a10-a3fd-df441a51794f)

**Comment by direded** [comment]
Any solutions? Im on Win 11 and have the same error.
