### ISSUE TITLE
Crashes ProcessHacker

### ISSUE THREAD

**Issue by DebugView12** [btbd/access#7]
I am using Cheat Engine 7.1 winver 1909, I loaded the driver and in debugview it shows [dbg] sucess. I injected the DLL into CE but when opening memory view on protected processes it still doesn't show anything so I decided to test on processhacker and whenever I open module list on a process in processhacker it crashes. Edit: on CE it gets stuck on this https://prnt.sc/tymana on memory view window

**Comment by btbd** [comment]
@DebugView12 Unfortunately I'm not sure why CE is getting stuck on symbol parsing -- I just tested on 1909 with CE 7.1 and it worked fine.

However, I only tested this project on Cheat Engine, ReClass, and Task Explorer. So I've just looked at ProcessHacker and my NtQueryVirtualMemory wrapper was missing a relative pointer adjustment for `MemoryMappedFilenameInformation`. See if the latest commit fixes that for you.

**Comment by DebugView12** [comment]
Thank you for adding that fix for process hacker. I realised it does work I am able to scan for values etc but cannot use memory view it either gets stuck on loading symbols or takes ages to load like 1% per 2 minutes. Anyways thanks for your work btbd.
